# Generated by Django 3.2 on 2021-04-26 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=20)),
                ('ename', models.CharField(max_length=100)),
                ('edate_of_birth', models.DateField()),
                ('edate_of_employment', models.DateField()),
                ('eposition', models.CharField(max_length=28)),
                ('edepartment', models.CharField(max_length=28)),
                ('esalary', models.CharField(max_length=8)),
                ('esupervisors', models.CharField(max_length=28)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
